# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DRY | KISS
email: lizhenhua230@gmail.com
description: >
 记录前端开发的点点滴滴，不断学习成长!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhenhua-lee.github.com" # the base hostname & protocol for your site
github_username:  zhenhua-lee

permalink: none
# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
